services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: labuser
      MYSQL_PASSWORD: labpass
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mysql-network

  mysql_to_cloud:
    build: ./mysql_to_cloud
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: labuser
      MYSQL_PASSWORD: labpass
      MYSQL_DATABASE: mydb
      MQTT_BROKER: test.mosquitto.org
      MQTT_PORT: 1883
      PLAYER_ID: 33
      MQTT_QOS: 2
      GAME_ID: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - mysql-network



  # mongodb_to_mysql:
  #   build: ./mongodb_to_mysql
  #   depends_on:
  #     - mysql
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: labuser
  #     MYSQL_PASSWORD: labpass
  #     MYSQL_DATABASE: labirinto_mysql
  #     MQTT_BROKER: test.mosquitto.org
  #     MQTT_PORT: 1883
  #     PLAYER_ID: 33
  #     MQTT_QOS: 2
  #     GAME_ID: 1
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   restart: always
  #   networks:
  #     - mysql-network

volumes:
  mysql_data:

networks:
  mysql-network:
